name: Build/Test and Deploy

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  go-build:
    uses: ./.github/workflows/go.yml
  vite-build:
    uses: ./.github/workflows/vite.yml
  deploy:
    needs: [go-build, vite-build]
    runs-on: ubuntu-latest
    steps:
    - name: Download Go Build artifact
      uses: actions/download-artifact@v4
      with:
        name: go-artifact
        path: ./build/backend
    - name: ls
      run: ls -lah
    - name: rsync deployments
      uses: burnett01/rsync-deployments@7.0.0
      with:
        path: ./build/
        switches: -avzr --delete
        remote_path: /srv/www/portfolio/
        remote_host: eilefsen.no
        remote_user: fedora
        remote_key: ${{ secrets.DEPLOY_KEY }}    
